version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "rm -f shared/pids/puma.pid && bundle exec rails s -b '0.0.0.0'"
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: $RAILS_ENV
volumes:
  bundle: